/*
Lichess.org API reference

# Introduction Welcome to the reference for the Lichess API! Lichess is free/libre, open-source chess server powered by volunteers and donations. - Get help in the [Lichess Discord channel](https://discord.gg/lichess) - API demo app with OAuth2 login, gameplay, and more: [source](https://github.com/lichess-org/api-demo) / [demo](https://lichess-org.github.io/api-demo/) - [Contribute to this documentation on Github](https://github.com/lichess-org/api) - Check out [Lichess widgets to embed in your website](https://lichess.org/developers) - [Download all Lichess rated games](https://database.lichess.org/) - [Download all Lichess puzzles with themes, ratings and votes](https://database.lichess.org/#puzzles)  ## Endpoint All requests go to `https://lichess.org` (unless otherwise specified).  ## Clients - [Python general API](https://github.com/ZackClements/berserk) - [MicroPython general API](https://github.com/mkomon/uberserk) - [Python general API - async](https://pypi.org/project/async-lichess-sdk) - [Python Lichess Bot](https://github.com/ShailChoksi/lichess-bot) - [Python Board API for Certabo](https://github.com/haklein/certabo-lichess) - [Java general API](https://github.com/tors42/chariot)  ## Rate limiting All requests are rate limited using various strategies, to ensure the API remains responsive for everyone. Only make one request at a time. If you receive an HTTP response with a [429 status](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#429), please wait a full minute before resuming API usage.  ## Streaming with ND-JSON Some API endpoints stream their responses as [Newline Delimited JSON a.k.a. **nd-json**](http://ndjson.org/), with one JSON object per line.  Here's a [JavaScript utility function](https://gist.github.com/ornicar/a097406810939cf7be1df8ea30e94f3e) to help reading NDJSON streamed responses. 

API version: 2.0.0
Contact: contact@lichess.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// ApiExternalEngineAnalyseRequest struct for ApiExternalEngineAnalyseRequest
type ApiExternalEngineAnalyseRequest struct {
	ClientSecret interface{} `json:"clientSecret"`
	Work ExternalEngineWork `json:"work"`
}

// NewApiExternalEngineAnalyseRequest instantiates a new ApiExternalEngineAnalyseRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiExternalEngineAnalyseRequest(clientSecret interface{}, work ExternalEngineWork) *ApiExternalEngineAnalyseRequest {
	this := ApiExternalEngineAnalyseRequest{}
	this.ClientSecret = clientSecret
	this.Work = work
	return &this
}

// NewApiExternalEngineAnalyseRequestWithDefaults instantiates a new ApiExternalEngineAnalyseRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiExternalEngineAnalyseRequestWithDefaults() *ApiExternalEngineAnalyseRequest {
	this := ApiExternalEngineAnalyseRequest{}
	return &this
}

// GetClientSecret returns the ClientSecret field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *ApiExternalEngineAnalyseRequest) GetClientSecret() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.ClientSecret
}

// GetClientSecretOk returns a tuple with the ClientSecret field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiExternalEngineAnalyseRequest) GetClientSecretOk() (*interface{}, bool) {
	if o == nil || o.ClientSecret == nil {
		return nil, false
	}
	return &o.ClientSecret, true
}

// SetClientSecret sets field value
func (o *ApiExternalEngineAnalyseRequest) SetClientSecret(v interface{}) {
	o.ClientSecret = v
}

// GetWork returns the Work field value
func (o *ApiExternalEngineAnalyseRequest) GetWork() ExternalEngineWork {
	if o == nil {
		var ret ExternalEngineWork
		return ret
	}

	return o.Work
}

// GetWorkOk returns a tuple with the Work field value
// and a boolean to check if the value has been set.
func (o *ApiExternalEngineAnalyseRequest) GetWorkOk() (*ExternalEngineWork, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Work, true
}

// SetWork sets field value
func (o *ApiExternalEngineAnalyseRequest) SetWork(v ExternalEngineWork) {
	o.Work = v
}

func (o ApiExternalEngineAnalyseRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.ClientSecret != nil {
		toSerialize["clientSecret"] = o.ClientSecret
	}
	if true {
		toSerialize["work"] = o.Work
	}
	return json.Marshal(toSerialize)
}

type NullableApiExternalEngineAnalyseRequest struct {
	value *ApiExternalEngineAnalyseRequest
	isSet bool
}

func (v NullableApiExternalEngineAnalyseRequest) Get() *ApiExternalEngineAnalyseRequest {
	return v.value
}

func (v *NullableApiExternalEngineAnalyseRequest) Set(val *ApiExternalEngineAnalyseRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableApiExternalEngineAnalyseRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableApiExternalEngineAnalyseRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiExternalEngineAnalyseRequest(val *ApiExternalEngineAnalyseRequest) *NullableApiExternalEngineAnalyseRequest {
	return &NullableApiExternalEngineAnalyseRequest{value: val, isSet: true}
}

func (v NullableApiExternalEngineAnalyseRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiExternalEngineAnalyseRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


