/*
Lichess.org API reference

# Introduction Welcome to the reference for the Lichess API! Lichess is free/libre, open-source chess server powered by volunteers and donations. - Get help in the [Lichess Discord channel](https://discord.gg/lichess) - API demo app with OAuth2 login, gameplay, and more: [source](https://github.com/lichess-org/api-demo) / [demo](https://lichess-org.github.io/api-demo/) - [Contribute to this documentation on Github](https://github.com/lichess-org/api) - Check out [Lichess widgets to embed in your website](https://lichess.org/developers) - [Download all Lichess rated games](https://database.lichess.org/) - [Download all Lichess puzzles with themes, ratings and votes](https://database.lichess.org/#puzzles)  ## Endpoint All requests go to `https://lichess.org` (unless otherwise specified).  ## Clients - [Python general API](https://github.com/ZackClements/berserk) - [MicroPython general API](https://github.com/mkomon/uberserk) - [Python general API - async](https://pypi.org/project/async-lichess-sdk) - [Python Lichess Bot](https://github.com/ShailChoksi/lichess-bot) - [Python Board API for Certabo](https://github.com/haklein/certabo-lichess) - [Java general API](https://github.com/tors42/chariot)  ## Rate limiting All requests are rate limited using various strategies, to ensure the API remains responsive for everyone. Only make one request at a time. If you receive an HTTP response with a [429 status](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#429), please wait a full minute before resuming API usage.  ## Streaming with ND-JSON Some API endpoints stream their responses as [Newline Delimited JSON a.k.a. **nd-json**](http://ndjson.org/), with one JSON object per line.  Here's a [JavaScript utility function](https://gist.github.com/ornicar/a097406810939cf7be1df8ea30e94f3e) to help reading NDJSON streamed responses. 

API version: 2.0.0
Contact: contact@lichess.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// ApiExternalEngineAcquire200Response struct for ApiExternalEngineAcquire200Response
type ApiExternalEngineAcquire200Response struct {
	Id interface{} `json:"id"`
	Work ExternalEngineWork `json:"work"`
	Engine ExternalEngine `json:"engine"`
}

// NewApiExternalEngineAcquire200Response instantiates a new ApiExternalEngineAcquire200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewApiExternalEngineAcquire200Response(id interface{}, work ExternalEngineWork, engine ExternalEngine) *ApiExternalEngineAcquire200Response {
	this := ApiExternalEngineAcquire200Response{}
	this.Id = id
	this.Work = work
	this.Engine = engine
	return &this
}

// NewApiExternalEngineAcquire200ResponseWithDefaults instantiates a new ApiExternalEngineAcquire200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewApiExternalEngineAcquire200ResponseWithDefaults() *ApiExternalEngineAcquire200Response {
	this := ApiExternalEngineAcquire200Response{}
	return &this
}

// GetId returns the Id field value
// If the value is explicit nil, the zero value for interface{} will be returned
func (o *ApiExternalEngineAcquire200Response) GetId() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}

	return o.Id
}

// GetIdOk returns a tuple with the Id field value
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *ApiExternalEngineAcquire200Response) GetIdOk() (*interface{}, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return &o.Id, true
}

// SetId sets field value
func (o *ApiExternalEngineAcquire200Response) SetId(v interface{}) {
	o.Id = v
}

// GetWork returns the Work field value
func (o *ApiExternalEngineAcquire200Response) GetWork() ExternalEngineWork {
	if o == nil {
		var ret ExternalEngineWork
		return ret
	}

	return o.Work
}

// GetWorkOk returns a tuple with the Work field value
// and a boolean to check if the value has been set.
func (o *ApiExternalEngineAcquire200Response) GetWorkOk() (*ExternalEngineWork, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Work, true
}

// SetWork sets field value
func (o *ApiExternalEngineAcquire200Response) SetWork(v ExternalEngineWork) {
	o.Work = v
}

// GetEngine returns the Engine field value
func (o *ApiExternalEngineAcquire200Response) GetEngine() ExternalEngine {
	if o == nil {
		var ret ExternalEngine
		return ret
	}

	return o.Engine
}

// GetEngineOk returns a tuple with the Engine field value
// and a boolean to check if the value has been set.
func (o *ApiExternalEngineAcquire200Response) GetEngineOk() (*ExternalEngine, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Engine, true
}

// SetEngine sets field value
func (o *ApiExternalEngineAcquire200Response) SetEngine(v ExternalEngine) {
	o.Engine = v
}

func (o ApiExternalEngineAcquire200Response) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if true {
		toSerialize["work"] = o.Work
	}
	if true {
		toSerialize["engine"] = o.Engine
	}
	return json.Marshal(toSerialize)
}

type NullableApiExternalEngineAcquire200Response struct {
	value *ApiExternalEngineAcquire200Response
	isSet bool
}

func (v NullableApiExternalEngineAcquire200Response) Get() *ApiExternalEngineAcquire200Response {
	return v.value
}

func (v *NullableApiExternalEngineAcquire200Response) Set(val *ApiExternalEngineAcquire200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableApiExternalEngineAcquire200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableApiExternalEngineAcquire200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableApiExternalEngineAcquire200Response(val *ApiExternalEngineAcquire200Response) *NullableApiExternalEngineAcquire200Response {
	return &NullableApiExternalEngineAcquire200Response{value: val, isSet: true}
}

func (v NullableApiExternalEngineAcquire200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableApiExternalEngineAcquire200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


