/*
Lichess.org API reference

# Introduction Welcome to the reference for the Lichess API! Lichess is free/libre, open-source chess server powered by volunteers and donations. - Get help in the [Lichess Discord channel](https://discord.gg/lichess) - API demo app with OAuth2 login, gameplay, and more: [source](https://github.com/lichess-org/api-demo) / [demo](https://lichess-org.github.io/api-demo/) - [Contribute to this documentation on Github](https://github.com/lichess-org/api) - Check out [Lichess widgets to embed in your website](https://lichess.org/developers) - [Download all Lichess rated games](https://database.lichess.org/) - [Download all Lichess puzzles with themes, ratings and votes](https://database.lichess.org/#puzzles)  ## Endpoint All requests go to `https://lichess.org` (unless otherwise specified).  ## Clients - [Python general API](https://github.com/ZackClements/berserk) - [MicroPython general API](https://github.com/mkomon/uberserk) - [Python general API - async](https://pypi.org/project/async-lichess-sdk) - [Python Lichess Bot](https://github.com/ShailChoksi/lichess-bot) - [Python Board API for Certabo](https://github.com/haklein/certabo-lichess) - [Java general API](https://github.com/tors42/chariot)  ## Rate limiting All requests are rate limited using various strategies, to ensure the API remains responsive for everyone. Only make one request at a time. If you receive an HTTP response with a [429 status](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#429), please wait a full minute before resuming API usage.  ## Streaming with ND-JSON Some API endpoints stream their responses as [Newline Delimited JSON a.k.a. **nd-json**](http://ndjson.org/), with one JSON object per line.  Here's a [JavaScript utility function](https://gist.github.com/ornicar/a097406810939cf7be1df8ea30e94f3e) to help reading NDJSON streamed responses. 

API version: 2.0.0
Contact: contact@lichess.org
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// PuzzleRoundJson struct for PuzzleRoundJson
type PuzzleRoundJson struct {
	Id interface{} `json:"id,omitempty"`
	Date interface{} `json:"date,omitempty"`
	Win interface{} `json:"win,omitempty"`
	PuzzleRating interface{} `json:"puzzleRating,omitempty"`
}

// NewPuzzleRoundJson instantiates a new PuzzleRoundJson object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPuzzleRoundJson() *PuzzleRoundJson {
	this := PuzzleRoundJson{}
	return &this
}

// NewPuzzleRoundJsonWithDefaults instantiates a new PuzzleRoundJson object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPuzzleRoundJsonWithDefaults() *PuzzleRoundJson {
	this := PuzzleRoundJson{}
	return &this
}

// GetId returns the Id field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PuzzleRoundJson) GetId() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Id
}

// GetIdOk returns a tuple with the Id field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PuzzleRoundJson) GetIdOk() (*interface{}, bool) {
	if o == nil || o.Id == nil {
		return nil, false
	}
	return &o.Id, true
}

// HasId returns a boolean if a field has been set.
func (o *PuzzleRoundJson) HasId() bool {
	if o != nil && o.Id != nil {
		return true
	}

	return false
}

// SetId gets a reference to the given interface{} and assigns it to the Id field.
func (o *PuzzleRoundJson) SetId(v interface{}) {
	o.Id = v
}

// GetDate returns the Date field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PuzzleRoundJson) GetDate() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Date
}

// GetDateOk returns a tuple with the Date field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PuzzleRoundJson) GetDateOk() (*interface{}, bool) {
	if o == nil || o.Date == nil {
		return nil, false
	}
	return &o.Date, true
}

// HasDate returns a boolean if a field has been set.
func (o *PuzzleRoundJson) HasDate() bool {
	if o != nil && o.Date != nil {
		return true
	}

	return false
}

// SetDate gets a reference to the given interface{} and assigns it to the Date field.
func (o *PuzzleRoundJson) SetDate(v interface{}) {
	o.Date = v
}

// GetWin returns the Win field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PuzzleRoundJson) GetWin() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.Win
}

// GetWinOk returns a tuple with the Win field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PuzzleRoundJson) GetWinOk() (*interface{}, bool) {
	if o == nil || o.Win == nil {
		return nil, false
	}
	return &o.Win, true
}

// HasWin returns a boolean if a field has been set.
func (o *PuzzleRoundJson) HasWin() bool {
	if o != nil && o.Win != nil {
		return true
	}

	return false
}

// SetWin gets a reference to the given interface{} and assigns it to the Win field.
func (o *PuzzleRoundJson) SetWin(v interface{}) {
	o.Win = v
}

// GetPuzzleRating returns the PuzzleRating field value if set, zero value otherwise (both if not set or set to explicit null).
func (o *PuzzleRoundJson) GetPuzzleRating() interface{} {
	if o == nil {
		var ret interface{}
		return ret
	}
	return o.PuzzleRating
}

// GetPuzzleRatingOk returns a tuple with the PuzzleRating field value if set, nil otherwise
// and a boolean to check if the value has been set.
// NOTE: If the value is an explicit nil, `nil, true` will be returned
func (o *PuzzleRoundJson) GetPuzzleRatingOk() (*interface{}, bool) {
	if o == nil || o.PuzzleRating == nil {
		return nil, false
	}
	return &o.PuzzleRating, true
}

// HasPuzzleRating returns a boolean if a field has been set.
func (o *PuzzleRoundJson) HasPuzzleRating() bool {
	if o != nil && o.PuzzleRating != nil {
		return true
	}

	return false
}

// SetPuzzleRating gets a reference to the given interface{} and assigns it to the PuzzleRating field.
func (o *PuzzleRoundJson) SetPuzzleRating(v interface{}) {
	o.PuzzleRating = v
}

func (o PuzzleRoundJson) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if o.Id != nil {
		toSerialize["id"] = o.Id
	}
	if o.Date != nil {
		toSerialize["date"] = o.Date
	}
	if o.Win != nil {
		toSerialize["win"] = o.Win
	}
	if o.PuzzleRating != nil {
		toSerialize["puzzleRating"] = o.PuzzleRating
	}
	return json.Marshal(toSerialize)
}

type NullablePuzzleRoundJson struct {
	value *PuzzleRoundJson
	isSet bool
}

func (v NullablePuzzleRoundJson) Get() *PuzzleRoundJson {
	return v.value
}

func (v *NullablePuzzleRoundJson) Set(val *PuzzleRoundJson) {
	v.value = val
	v.isSet = true
}

func (v NullablePuzzleRoundJson) IsSet() bool {
	return v.isSet
}

func (v *NullablePuzzleRoundJson) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePuzzleRoundJson(val *PuzzleRoundJson) *NullablePuzzleRoundJson {
	return &NullablePuzzleRoundJson{value: val, isSet: true}
}

func (v NullablePuzzleRoundJson) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePuzzleRoundJson) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


