openapi: 3.1.0
info:
  contact:
    email: contact@lichess.org
    name: Lichess.org API
    url: https://lichess.org/api
  description: |
    # Introduction
    Welcome to the reference for the Lichess API! Lichess is free/libre,
    open-source chess server powered by volunteers and donations.
    - Get help in the [Lichess Discord channel](https://discord.gg/lichess)
    - API demo app with OAuth2 login, gameplay, and more: [source](https://github.com/lichess-org/api-demo) / [demo](https://lichess-org.github.io/api-demo/)
    - [Contribute to this documentation on Github](https://github.com/lichess-org/api)
    - Check out [Lichess widgets to embed in your website](https://lichess.org/developers)
    - [Download all Lichess rated games](https://database.lichess.org/)
    - [Download all Lichess puzzles with themes, ratings and votes](https://database.lichess.org/#puzzles)

    ## Endpoint
    All requests go to `https://lichess.org` (unless otherwise specified).

    ## Clients
    - [Python general API](https://github.com/ZackClements/berserk)
    - [MicroPython general API](https://github.com/mkomon/uberserk)
    - [Python general API - async](https://pypi.org/project/async-lichess-sdk)
    - [Python Lichess Bot](https://github.com/ShailChoksi/lichess-bot)
    - [Python Board API for Certabo](https://github.com/haklein/certabo-lichess)
    - [Java general API](https://github.com/tors42/chariot)

    ## Rate limiting
    All requests are rate limited using various strategies,
    to ensure the API remains responsive for everyone.
    Only make one request at a time.
    If you receive an HTTP response with a [429 status](https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#429),
    please wait a full minute before resuming API usage.

    ## Streaming with ND-JSON
    Some API endpoints stream their responses as [Newline Delimited JSON a.k.a. **nd-json**](http://ndjson.org/), with one JSON object per line.

    Here's a [JavaScript utility function](https://gist.github.com/ornicar/a097406810939cf7be1df8ea30e94f3e) to help reading NDJSON streamed responses.
  title: Lichess.org API reference
  version: 2.0.0
  x-logo:
    url: https://lichess1.org/assets/logo/lichess-pad12.svg
servers:
- url: https://lichess.org
tags:
- description: |
    Read and write account information and preferences.
    <https://lichess.org/account/preferences/game-display>
  name: Account
- description: |
    Access registered users on Lichess.
    <https://lichess.org/player>

    - Each user blog exposes an atom (RSS) feed, like <https://lichess.org/@/thibault/blog.atom>
    - User blogs mashup feed: https://lichess.org/blog/community.atom
    - User blogs mashup feed for a language: https://lichess.org/blog/community/fr.atom
  name: Users
- description: |
    Access relations between users.
  name: Relations
- description: |
    Access games played on Lichess.
    <https://lichess.org/games>
  name: Games
- description: |
    Access Lichess TV channels and games.
    <https://lichess.org/tv> & <https://lichess.org/games>
  name: TV
- description: |
    Access Lichess [puzzle history and dashboard](https://lichess.org/training).

    Our collection of puzzles is in the public domain, you can [download it here](https://database.lichess.org/#puzzles).
    For a list of our puzzle themes with their description, check out the [theme translation file](https://github.com/ornicar/lila/blob/master/translation/source/puzzleTheme.xml).
    The daily puzzle can be [posted in your slack workspace](https://lichess.org/daily-puzzle-slack).
  name: Puzzles
- description: |
    Access and manage Lichess teams and their members.
    <https://lichess.org/team>
  name: Teams
- description: "Play on Lichess with physical boards and third-party clients.\n  Works\
    \ with normal Lichess accounts. Engine play or assistance is [forbidden](https://lichess.org/page/fair-play).\n\
    \n\n### Features\n - [Stream incoming chess moves](#operation/boardGameStream)\n\
    \ - [Play chess moves](#operation/boardGameMove)\n - [Read](#operation/boardGameStream)\
    \ and [write](#operation/boardGameChatPost) in the player and spectator chats\n\
    \ - [Receive](#operation/apiStreamEvent), [create](#operation/challengeCreate)\
    \ and [accept](#operation/challengeAccept) (or [decline](#operation/challengeDecline))\
    \ challenges\n - [Abort](#operation/boardGameAbort) and [resign](#operation/boardGameResign)\
    \ games\n - Compatible with normal Lichess accounts\n\n \n### Restrictions\n -\
    \ Engine assistance, or any kind of outside help, is [forbidden](https://lichess.org/page/fair-play)\n\
    \ - Time controls: [Rapid, Classical and Correspondence](https://lichess.org/faq#time-controls)\
    \ only.\n   For direct challenges and games vs AI, Blitz is also possible.\n\n\
    ### Links\n - [Announcement](https://lichess.org/blog/XlRW5REAAB8AUJJ-/welcome-lichess-boards)\n\
    \ - [Implementation example](https://github.com/lichess-org/api-demo) and [live\
    \ demo](https://lichess-org.github.io/api-demo/)\n\n  - [Certabo support](https://github.com/haklein/certabo-lichess)\n\
    \ - [Lichs (play from command-line)](https://github.com/Cqsi/lichs)\n - [Lichess\
    \ discord bot](https://top.gg/bot/707287095911120968)"
  name: Board
- description: |-
    Play on Lichess as a bot. Allows engine play.
      Read the [blog post announcement of lichess bots](https://lichess.org/blog/WvDNticAAMu_mHKP/welcome-lichess-bots).

      Only works with [Bot accounts](#operation/botAccountUpgrade).


    ### Features
     - [Stream incoming chess moves](#operation/botGameStream)
     - [Play chess moves](#operation/botGameMove)
     - [Read](#operation/botGameStream) and [write](#operation/botGameChat) in the player and spectator chats
     - [Receive](#operation/apiStreamEvent), [create](#operation/challengeCreate) and [accept](#operation/challengeAccept) (or [decline](#operation/challengeDecline)) challenges
     - [Abort](#operation/botGameAbort) and [resign](#operation/botGameResign) games
     - Engine assistance is [allowed](https://lichess.org/page/fair-play)

    ### Restrictions
     - Bots can only play challenge games:  pools and tournaments are off-limits
     - Bots cannot play UltraBullet (¼+0) because it requires making too many requests. But 0+1 and ½+0 are allowed.

    ### Integrations
     - [Python3 lichess-bot](https://github.com/ShailChoksi/lichess-bot) (official)
     - [JavaScript bot-o-tron](https://github.com/tailuge/bot-o-tron)
     - [Golang lichess-bot](https://github.com/dolegi/lichess-bot)
     - [Electronic Chessboard](http://www.oliviermercier.com/res/projects/chessboard/)  - Yours? Please make [an issue or pull request](https://github.com/lichess-org/api).

    ### Links
     - [Announcement](https://lichess.org/blog/WvDNticAAMu_mHKP/welcome-lichess-bots)
     - Join the [Lichess Bots team](https://lichess.org/team/lichess-bots) with your bot account
     - [Get help in the discord channel](https://discord.gg/quwueFd)
     - Watch [Lichess Bot TV](https://lichess.org/tv/bot)
  name: Bot
- description: |
    Send and receive challenges to play.

    To create a lot of challenges, consider [bulk pairing](#operation/bulkPairingCreate) instead.
  name: Challenges
- description: |
    Create many games for other players.

    These endpoints are intended for tournament organisers.
  name: Bulk pairings
- description: |
    Access Arena tournaments played on Lichess.
    [Official Arena tournaments](https://lichess.org/tournament) are maintained by Lichess,
    but you can [create your own Arena tournaments](https://lichess.org/tournament/new) as well.
  name: Arena tournaments
- description: |
    Access Swiss tournaments played on Lichess.
    [Read more about Swiss tournaments.](https://lichess.org/swiss).
  name: Swiss tournaments
- description: |
    Access simuls played on Lichess.
    <https://lichess.org/simul>
  name: Simuls
- description: |
    Access Lichess studies.
    <https://lichess.org/study>
  name: Studies
- description: |
    Private messages with other players.
    <https://lichess.org/inbox>
  name: Messaging
- description: |
    Relay chess events on Lichess.
    [Official broadcasts](https://lichess.org/broadcast) are maintained by Lichess,
    but you can [create your own broadcasts](https://lichess.org/broadcast/new) to cover any live game or chess event.
    You will need to publish PGN on a public URL so that Lichess can pull updates from it.
    Alternatively, you can push PGN updates to Lichess using this API.

    Broadcasts are organized in tournaments, which have several rounds, which have several games.
    You must first create a tournament, then you can add rounds to them.
  name: Broadcasts
- description: |
    Access Lichess cloud evaluations database.
    <https://lichess.org/analysis>
  name: Analysis
- description: |
    **This API is in alpha and subject to change.**

    Use or provide external engine analysis.

    External engines can provide analysis on pages like the
    [analysis board](https://lichess.org/analysis), running as a service
    outside of the browser, or even on a different machine.
  name: External engine
- description: |
    Lookup positions from the [Lichess opening explorer](https://lichess.org/analysis#explorer).

    Runs <https://github.com/niklasf/lila-openingexplorer>.

    **The endpoint hostname is not lichess.org but explorer.lichess.ovh.**
  name: Opening Explorer
- description: |
    Lookup positions from the [Lichess tablebase server](https://lichess.org/blog/W3WeMyQAACQAdfAL/7-piece-syzygy-tablebases-are-complete).

    **The endpoint hostname is not lichess.org but tablebase.lichess.ovh.**
  name: Tablebase
- description: |
    Obtaining and revoking OAuth tokens.

    [Read about the Lichess API authentication methods and code examples](https://github.com/lichess-org/api/blob/master/example/README.md).
  name: OAuth
paths:
  /api/users/status:
    get:
      description: |
        Read the `online`, `playing` and `streaming` flags of several users.

        This API is very fast and cheap on lichess side.
        So you can call it quite often (like once every 5 seconds).

        Use it to track players and know when they're connected on lichess and playing games.
      operationId: apiUsersStatus
      security: []
      summary: Get real-time users status
      tags:
      - Users
  /api/player:
    get:
      description: |
        Get the top 10 players for each speed and variant.

        See <https://lichess.org/player>.
      operationId: player
      security: []
      summary: Get all top 10
      tags:
      - Users
  /api/player/top/{nb}/{perfType}:
    get:
      description: |
        Get the leaderboard for a single speed or variant (a.k.a. `perfType`).
        There is no leaderboard for correspondence or puzzles.

        See <https://lichess.org/player/top/200/bullet>.
      operationId: playerTopNbPerfType
      security: []
      summary: Get one leaderboard
      tags:
      - Users
  /api/user/{username}:
    get:
      description: |
        Read public data of a user.

        If the request is [authenticated with OAuth2](#section/Authentication),
        then extra fields might be present in the response: `followable`, `following`, `blocking`, `followsYou`.
      operationId: apiUser
      security:
      - OAuth2: []
      summary: Get user public data
      tags:
      - Users
  /api/user/{username}/rating-history:
    get:
      description: |
        Read rating history of a user, for all perf types.
        There is at most one entry per day.
        Format of an entry is `[year, month, day, rating]`.
        `month` starts at zero (January).
      operationId: apiUserRatingHistory
      security: []
      summary: Get rating history of a user
      tags:
      - Users
  /api/user/{username}/perf/{perf}:
    get:
      description: |
        Read performance statistics of a user, for a single performance.
        Similar to the [performance pages on the website](https://lichess.org/@/thibault/perf/bullet).
      operationId: apiUserPerf
      security: []
      summary: Get performance statistics of a user
      tags:
      - Users
  /api/user/{username}/activity:
    get:
      description: |
        Read data to generate the activity feed of a user.
      operationId: apiUserActivity
      security: []
      summary: Get user activity
      tags:
      - Users
  /api/puzzle/daily:
    get:
      description: |
        Get the daily Lichess puzzle in JSON format.

        Alternatively, you can [post it in your slack workspace](https://lichess.org/daily-puzzle-slack).
      operationId: apiPuzzleDaily
      security: []
      summary: Get the daily puzzle
      tags:
      - Puzzles
  /api/puzzle/{id}:
    get:
      description: Get a single Lichess puzzle in JSON format.
      operationId: apiPuzzleId
      security: []
      summary: Get a puzzle by its ID
      tags:
      - Puzzles
  /api/puzzle/activity:
    get:
      description: |
        Download your puzzle activity in [ndjson](#section/Introduction/Streaming-with-ND-JSON) format.

        Puzzle activity is sorted by reverse chronological order (most recent first)

        We recommend streaming the response, for it can be very long.
      operationId: apiPuzzleActivity
      security:
      - OAuth2:
        - puzzle:read
      summary: Get your puzzle activity
      tags:
      - Puzzles
  /api/puzzle/dashboard/{days}:
    get:
      description: |
        Download your [puzzle dashboard](https://lichess.org/training/dashboard/30/dashboard) as JSON.

        Also includes all puzzle themes played, with aggregated results.

        Allows re-creating the [improvement/strengths](https://lichess.org/training/dashboard/30/improvementAreas) interfaces.
      operationId: apiPuzzleDashboard
      security:
      - OAuth2:
        - puzzle:read
      summary: Get your puzzle dashboard
      tags:
      - Puzzles
  /api/storm/dashboard/{username}:
    get:
      description: |
        Download the [storm dashboard](https://lichess.org/storm/dashboard/mrbasso) of any player as JSON.

        Contains the aggregated highscores, and the history of storm runs aggregated by days.

        Use `?days=0` if you only care about the highscores.
      operationId: apiStormDashboard
      security: []
      summary: Get the storm dashboard of a player
      tags:
      - Puzzles
  /api/racer:
    post:
      description: |
        Create a new private [puzzle race](https://lichess.org/racer).
        The Lichess user who creates the race must join the race page,
        and manually start the race when enough players have joined.

        - <https://lichess.org/racer>
      operationId: racerPost
      security:
      - OAuth2:
        - racer:write
      summary: Create and join a puzzle race
      tags:
      - Puzzles
  /api/users:
    post:
      description: |
        Get up to 300 users by their IDs. Users are returned in the same order as the IDs.

        The method is `POST` so a longer list of IDs can be sent in the request body.
      operationId: apiUsers
      security: []
      summary: Get users by ID
      tags:
      - Users
  /api/account:
    get:
      description: |
        Public information about the logged in user.
      operationId: accountMe
      security:
      - OAuth2: []
      summary: Get my profile
      tags:
      - Account
  /api/account/email:
    get:
      description: |
        Read the email address of the logged in user.
      operationId: accountEmail
      security:
      - OAuth2:
        - email:read
      summary: Get my email address
      tags:
      - Account
  /api/account/preferences:
    get:
      description: |
        Read the preferences of the logged in user.

        - <https://lichess.org/account/preferences/game-display>
        - <https://github.com/ornicar/lila/blob/master/modules/pref/src/main/Pref.scala>
      operationId: account
      security:
      - OAuth2:
        - preference:read
      summary: Get my preferences
      tags:
      - Account
  /api/account/kid:
    get:
      description: |
        Read the kid mode status of the logged in user.

        - <https://lichess.org/account/kid>
      operationId: accountKid
      security:
      - OAuth2:
        - preference:read
      summary: Get my kid mode status
      tags:
      - Account
    post:
      description: |
        Set the kid mode status of the logged in user.

        - <https://lichess.org/account/kid>
      operationId: accountKidPost
      security:
      - OAuth2:
        - preference:write
      summary: Set my kid mode status
      tags:
      - Account
  /game/export/{gameId}:
    get:
      description: |
        Download one game in either PGN or JSON format.

        Ongoing games have their last 3 moves omitted, after move 5.
      operationId: gamePgn
      security: []
      summary: Export one game
      tags:
      - Games
  /api/user/{username}/current-game:
    get:
      description: |
        Download the ongoing game, or the last game played, of a user.
        Available in either PGN or JSON format.
        If the game is ongoing, the 3 last moves are omitted.
      operationId: apiUserCurrentGame
      security: []
      summary: Export ongoing game of a user
      tags:
      - Games
  /api/games/user/{username}:
    get:
      description: |
        Download all games of any user in PGN or [ndjson](#section/Introduction/Streaming-with-ND-JSON) format.

        Games are sorted by reverse chronological order (most recent first).

        We recommend streaming the response, for it can be very long.
        <https://lichess.org/@/german11> for instance has more than 500,000 games.

        The game stream is throttled, depending on who is making the request:
          - Anonymous request: 20 games per second
          - [OAuth2 authenticated](#section/Authentication) request: 30 games per second
          - Authenticated, downloading your own games: 60 games per second
      operationId: apiGamesUser
      security:
      - OAuth2: []
      summary: Export games of a user
      tags:
      - Games
  /api/games/export/_ids:
    post:
      description: |
        Download games by IDs in PGN or [ndjson](#section/Introduction/Streaming-with-ND-JSON) format, depending on the request Accept header.

        Games are sorted by reverse chronological order (most recent first)

        The method is `POST` so a longer list of IDs can be sent in the request body.

        300 IDs can be submitted.

        Ongoing games have their last 3 moves omitted, after move 5.
      operationId: gamesExportIds
      security: []
      summary: Export games by IDs
      tags:
      - Games
  /api/stream/games-by-users:
    post:
      description: |
        Stream the games played between a list of users, in real time.
        Only games where **both players** are part of the list are included.

        The stream emits an event each time a game is started or finished.

        To also get all current ongoing games at the beginning of the stream, use the `withCurrentGames` flag.

        Games are streamed as [ndjson](#section/Introduction/Streaming-with-ND-JSON).

        Maximum number of users: 300.

        The method is `POST` so a longer list of IDs can be sent in the request body.
      operationId: gamesByUsers
      security: []
      summary: Stream games of users
      tags:
      - Games
  /api/stream/games/{streamId}:
    post:
      description: |
        Creates a stream of games from an arbitrary streamId, and a list of game IDs.

        The stream first outputs the games that already exists, then emits an event each time a game is started or finished.

        Games are streamed as [ndjson](#section/Introduction/Streaming-with-ND-JSON).

        Maximum number of games: 500 for anonymous requests, or 1000 for [OAuth2 authenticated](#section/Authentication) requests.

        While the stream is open, it is possible to [add new game IDs to watch](#operation/gamesByIdsAdd).
      operationId: gamesByIds
      security: []
      summary: Stream games by IDs
      tags:
      - Games
  /api/stream/games/{streamId}/add:
    post:
      description: |
        Add new game IDs for [an existing stream](#operation/gamesByIds) to watch.
        The stream will immediately outputs the games that already exists, then emit an event each time a game is started or finished.
      operationId: gamesByIdsAdd
      security: []
      summary: Add game IDs to stream
      tags:
      - Games
  /api/account/playing:
    get:
      description: |
        Get the ongoing games of the current user.
        Real-time and correspondence games are included.
        The most urgent games are listed first.
      operationId: apiAccountPlaying
      security:
      - OAuth2: []
      summary: Get my ongoing games
      tags:
      - Games
  /api/stream/game/{id}:
    get:
      description: |
        Stream positions and moves of any ongoing game, in [ndjson](#section/Introduction/Streaming-with-ND-JSON).

        A description of the game is sent as a first message.
        Then a message is sent each time a move is played.
        Finally a description of the game is sent when it finishes, and the stream is closed.

        After move 5, the stream intentionally remains 3 moves behind the game status, as to prevent cheat bots from using this API.

        No more than 8 game streams can be opened at the same time from the same IP address.
      operationId: streamGame
      security: []
      summary: Stream moves of a game
      tags:
      - Games
  /api/import:
    post:
      description: |
        Import a game from PGN. See <https://lichess.org/paste>.

        Rate limiting: 200 games per hour for OAuth requests, 100 games per hour for anonymous requests.

        To broadcast ongoing games, consider [pushing to a broadcast instead](#operation/broadcastPush).
      operationId: gameImport
      security:
      - OAuth2: []
      summary: Import one game
      tags:
      - Games
  /api/tv/channels:
    get:
      description: |
        Get basic info about the best games being played for each speed and variant,
        but also computer games and bot games.

        See [lichess.org/tv](https://lichess.org/tv).
      operationId: tvChannels
      security: []
      summary: Get current TV games
      tags:
      - TV
  /api/tv/feed:
    get:
      description: |
        Stream positions and moves of the current [TV game](https://lichess.org/tv) in [ndjson](#section/Introduction/Streaming-with-ND-JSON).
        A summary of the game is sent as a first message, and when the featured game changes.

        Try it with `curl https://lichess.org/api/tv/feed`.
      operationId: tvFeed
      security: []
      summary: Stream current TV game
      tags:
      - TV
  /api/tv/{channel}:
    get:
      description: |
        Get a list of ongoing games for a given TV channel. Similar to [lichess.org/games](https://lichess.org/games).

        Available in PGN or [ndjson](#section/Introduction/Streaming-with-ND-JSON) format, depending on the request Accept header.
      operationId: tvChannelGames
      security: []
      summary: Get best ongoing games of a TV channel
      tags:
      - TV
  /api/tournament:
    get:
      description: |
        Get recently finished, ongoing, and upcoming tournaments.

        This API is used to display the [Lichess tournament schedule](https://lichess.org/tournament).
      operationId: apiTournament
      security: []
      summary: Get current tournaments
      tags:
      - Arena tournaments
    post:
      description: |
        Create a public or private Arena tournament.

        This endpoint mirrors the form on <https://lichess.org/tournament/new>.

        You can create up to 12 public tournaments per day, or 24 private tournaments.

        A team battle can be created by specifying the `teambBattleByTeam` argument.

        Additional restrictions:
          - clockTime + clockIncrement > 0
          - 15s and 0+1 variant tournaments cannot be rated
          - Clock time in comparison to tournament length must be reasonable: 3 <= (minutes * 60) / (96 * clockTime + 48 * clockIncrement + 15) <= 150
      operationId: apiTournamentPost
      security:
      - OAuth2:
        - tournament:write
      summary: Create a new Arena tournament
      tags:
      - Arena tournaments
  /api/tournament/{id}:
    get:
      description: |
        Get detailed info about recently finished, current, or upcoming tournament's duels, player standings, and other info.
      operationId: tournament
      security: []
      summary: Get info about an Arena tournament
      tags:
      - Arena tournaments
    post:
      description: |
        Update an Arena tournament.

        Be mindful not to make important changes to ongoing tournaments.

        Can be used to update a team battle.

        Additional restrictions:
          - clockTime + clockIncrement > 0
          - 15s and 0+1 variant tournaments cannot be rated
          - Clock time in comparison to tournament length must be reasonable: 3 <= (minutes * 60) / (96 * clockTime + 48 * clockIncrement + 15) <= 150
      operationId: apiTournamentUpdate
      security:
      - OAuth2:
        - tournament:write
      summary: Update an Arena tournament
      tags:
      - Arena tournaments
  /api/tournament/{id}/join:
    post:
      description: |
        Join an Arena tournament, possibly with a password and/or a team.
        Also unpauses if you had previously [paused](#operation/apiTournamentWithdraw) the tournament.
      operationId: apiTournamentJoin
      security:
      - OAuth2:
        - tournament:write
      summary: Join an Arena tournament
      tags:
      - Arena tournaments
  /api/tournament/{id}/withdraw:
    post:
      description: |
        Leave a future Arena tournament, or take a break on an ongoing Arena tournament.
        It's possible to join again later. Points and streaks are preserved.
      operationId: apiTournamentWithdraw
      security:
      - OAuth2:
        - tournament:write
      summary: Pause or leave an Arena tournament
      tags:
      - Arena tournaments
  /api/tournament/{id}/terminate:
    post:
      description: |
        Terminate an Arena tournament
      operationId: apiTournamentTerminate
      security:
      - OAuth2:
        - tournament:write
      summary: Terminate an Arena tournament
      tags:
      - Arena tournaments
  /api/tournament/team-battle/{id}:
    post:
      description: |
        Set the teams and number of leaders of a team battle.

        To update the other attributes of a team battle, use the [tournament update endpoint](#operation/apiTournamentUpdate).
      operationId: apiTournamentTeamBattlePost
      security:
      - OAuth2:
        - tournament:write
      summary: Update a team battle
      tags:
      - Arena tournaments
  /api/tournament/{id}/games:
    get:
      description: |
        Download games of a tournament in PGN or [ndjson](#section/Introduction/Streaming-with-ND-JSON) format.

        Games are sorted by reverse chronological order (most recent first).

        The game stream is throttled, depending on who is making the request:
          - Anonymous request: 20 games per second
          - [OAuth2 authenticated](#section/Authentication) request: 30 games per second
      operationId: gamesByTournament
      security: []
      summary: Export games of an Arena tournament
      tags:
      - Arena tournaments
  /api/tournament/{id}/results:
    get:
      description: |
        Players of an Arena tournament, with their score and performance, sorted by rank (best first).

        **Players are streamed as [ndjson](#section/Introduction/Streaming-with-ND-JSON)**, i.e. one JSON object per line.

        If called on an ongoing tournament, results can be inconsistent
        due to ranking changes while the players are being streamed.
        Use on finished tournaments for guaranteed consistency.
      operationId: resultsByTournament
      security: []
      summary: Get results of an Arena tournament
      tags:
      - Arena tournaments
  /api/tournament/{id}/teams:
    get:
      description: |
        Teams of a team battle tournament, with top players, sorted by rank (best first).
      operationId: teamsByTournament
      security: []
      summary: Get team standing of a team battle
      tags:
      - Arena tournaments
  /api/user/{username}/tournament/created:
    get:
      description: |
        Get all tournaments created by a given user.

        Tournaments are sorted by reverse chronological order of start date (last starting first).

        Tournaments are streamed as [ndjson](#section/Introduction/Streaming-with-ND-JSON).
      operationId: apiUserNameTournamentCreated
      security: []
      summary: Get tournaments created by a user
      tags:
      - Arena tournaments
  /api/swiss/new/{teamId}:
    post:
      description: |
        Create a Swiss tournament for your team.

        This endpoint mirrors the Swiss tournament form from your team pagee.

        You can create up to 12 tournaments per day.

        Additional restrictions:
          - clock.limit + clock.increment > 0
          - 15s and 0+1 variant tournaments cannot be rated
      operationId: apiSwissNew
      security:
      - OAuth2:
        - tournament:write
      summary: Create a new Swiss tournament
      tags:
      - Swiss tournaments
  /api/swiss/{id}:
    get:
      description: |
        Get detailed info about a Swiss tournament.
      operationId: swiss
      security: []
      summary: Get info about a Swiss tournament
      tags:
      - Swiss tournaments
  /api/swiss/{id}/edit:
    post:
      description: |
        Update a Swiss tournament.

        Be mindful not to make important changes to ongoing tournaments.

        Additional restrictions:
          - clock.limit + clock.increment > 0
          - 15s and 0+1 variant tournaments cannot be rated
      operationId: apiSwissUpdate
      security:
      - OAuth2:
        - tournament:write
      summary: Update a Swiss tournament.
      tags:
      - Swiss tournaments
  /api/swiss/{id}/join:
    post:
      description: |
        Join a Swiss tournament, possibly with a password.
      operationId: apiSwissJoin
      security:
      - OAuth2:
        - tournament:write
      summary: Join a Swiss tournament
      tags:
      - Swiss tournaments
  /api/swiss/{id}/withdraw:
    post:
      description: |
        Leave a future Swiss tournament, or take a break on an ongoing Swiss tournament.
        It's possible to join again later. Points are preserved.
      operationId: apiSwissWithdraw
      security:
      - OAuth2:
        - tournament:write
      summary: Pause or leave a swiss tournament
      tags:
      - Swiss tournaments
  /api/swiss/{id}/terminate:
    post:
      description: |
        Terminate a Swiss tournament
      operationId: apiSwissTerminate
      security:
      - OAuth2:
        - tournament:write
      summary: Terminate a Swiss tournament
      tags:
      - Swiss tournaments
  /swiss/{id}.trf:
    get:
      description: |
        Download a tournament in the Tournament Report File format, the FIDE standard.

        Documentation: <https://www.fide.com/FIDE/handbook/C04Annex2_TRF16.pdf>

        Example: <https://lichess.org/swiss/j8rtJ5GL.trf>
      operationId: swissTrf
      security: []
      summary: Export TRF of a Swiss tournament
      tags:
      - Swiss tournaments
  /api/swiss/{id}/games:
    get:
      description: |
        Download games of a swiss tournament in PGN or [ndjson](#section/Introduction/Streaming-with-ND-JSON) format.

        Games are sorted by reverse chronological order (last round first).

        The game stream is throttled, depending on who is making the request:
          - Anonymous request: 20 games per second
          - [OAuth2 authenticated](#section/Authentication) request: 30 games per second
      operationId: gamesBySwiss
      security: []
      summary: Export games of a Swiss tournament
      tags:
      - Swiss tournaments
  /api/swiss/{id}/results:
    get:
      description: |
        Players of a swiss tournament, with their score and performance, sorted by rank (best first).

        Players are streamed as [ndjson](#section/Introduction/Streaming-with-ND-JSON).

        If called on an ongoing tournament, results can be inconsistent
        due to ranking changes while the players are being streamed.
        Use on finished tournaments for guaranteed consistency.
      operationId: resultsBySwiss
      security: []
      summary: Get results of a swiss tournament
      tags:
      - Swiss tournaments
  /api/team/{teamId}/swiss:
    get:
      description: |
        Get all swiss tournaments of a team.

        Tournaments are sorted by reverse chronological order of start date (last starting first).

        Tournaments are streamed as [ndjson](#section/Introduction/Streaming-with-ND-JSON).
      operationId: apiTeamSwiss
      security: []
      summary: Get team swiss tournaments
      tags:
      - Teams
      - Swiss tournaments
  /study/{studyId}/{chapterId}.pgn:
    get:
      description: |
        Download one study chapter in PGN format.
      operationId: studyChapterPgn
      security: []
      summary: Export one study chapter
      tags:
      - Studies
  /api/study/{studyId}.pgn:
    get:
      description: |
        Download all chapters of a study in PGN format.
      operationId: studyAllChaptersPgn
      security: []
      summary: Export all chapters
      tags:
      - Studies
  /study/by/{username}/export.pgn:
    get:
      description: |
        Download all chapters of all studies of a user in PGN format.

        If authenticated, then all public, unlisted, and private studies are included.

        If not, only public, listed studies are included.
      operationId: studyExportAllPgn
      security:
      - OAuth2:
        - study:read
      summary: Export all studies of a user
      tags:
      - Studies
  /api/broadcast:
    get:
      description: |
        Get all incoming, ongoing, and finished official broadcasts.
        The broadcasts are sorted by start date, most recent first.

        Broadcasts are streamed as [ndjson](#section/Introduction/Streaming-with-ND-JSON).
      operationId: broadcastIndex
      summary: Get official broadcasts
      tags:
      - Broadcasts
  /broadcast/new:
    post:
      description: |
        Create a new broadcast tournament to relay external games.
        This endpoint accepts the same form data as the [web form](https://lichess.org/broadcast/new).
      operationId: broadcastTourCreate
      security:
      - OAuth2:
        - study:write
      summary: Create a broadcast tournament
      tags:
      - Broadcasts
  /broadcast/{slug}/{broadcastTournamentId}:
    get:
      description: |
        Get information about a broadcast tournament.
      operationId: broadcastTourGet
      security:
      - OAuth2:
        - study:read
      summary: Get your broadcast tournament
      tags:
      - Broadcasts
  /broadcast/{broadcastTournamentId}/edit:
    post:
      description: |
        Update information about a broadcast tournament that you created.
        This endpoint accepts the same form data as the web form.
        All fields must be populated with data. Missing fields will override the broadcast with empty data.
      operationId: broadcastTourUpdate
      security:
      - OAuth2:
        - study:write
      summary: Update your broadcast tournament
      tags:
      - Broadcasts
  /broadcast/{broadcastTournamentId}/new:
    post:
      description: |
        Create a new broadcast round to relay external games.
        This endpoint accepts the same form data as the web form.
      operationId: broadcastRoundCreate
      security:
      - OAuth2:
        - study:write
      summary: Create a broadcast round
      tags:
      - Broadcasts
  /broadcast/{broadcastTournamentSlug}/{broadcastRoundSlug}/{broadcastRoundId}:
    get:
      description: |
        Get information about a broadcast round.
      operationId: broadcastRoundGet
      security:
      - OAuth2:
        - study:read
      summary: Get your broadcast round
      tags:
      - Broadcasts
  /broadcast/round/{broadcastRoundId}/edit:
    post:
      description: |
        Update information about a broadcast round that you created.
        This endpoint accepts the same form data as the web form.
        All fields must be populated with data. Missing fields will override the broadcast with empty data.
        For instance, if you omit `startDate`, then any pre-existing start date will be removed.
      operationId: broadcastRoundUpdate
      security:
      - OAuth2:
        - study:write
      summary: Update your broadcast round
      tags:
      - Broadcasts
  /broadcast/round/{broadcastRoundId}/push:
    post:
      description: |
        Update your broadcast with new PGN.
        Only for broadcast without a source URL.
      operationId: broadcastPush
      security:
      - OAuth2:
        - study:write
      summary: Push PGN to your broadcast round
      tags:
      - Broadcasts
  /api/stream/broadcast/round/{broadcastRoundId}.pgn:
    get:
      description: |
        This streaming endpoint first sends all games of a broadcast tournament in PGN format.

        Then, it waits for new moves to be played. As soon as it happens, the entire PGN of the game is sent to the stream.

        The stream will also send PGNs when games are added to the tournament.

        This is the best way to get updates about an ongoing tournament. Streaming means no polling,
        and no pollings means no latency, and minimum impact on the server.
      operationId: broadcastStreamRoundPgn
      security: []
      summary: Stream an ongoing broadcast tournament as PGN
      tags:
      - Broadcasts
  /api/broadcast/round/{broadcastRoundId}.pgn:
    get:
      description: |
        Download all games of a single round of a broadcast tournament in PGN format.

        You *could* poll this endpoint to get updates about a tournament, but it would be slow,
        and very inneficient.

        Instead, consider [streaming the tournament](#operation/broadcastStreamRoundPgn) to get
        a new PGN every time a game is updated, in real-time.
      operationId: broadcastRoundPgn
      security: []
      summary: Export one round as PGN
      tags:
      - Broadcasts
  /api/broadcast/{broadcastTournamentId}.pgn:
    get:
      description: |
        Download all games of all rounds of a broadcast in PGN format.

        You may want to [download only the games of a single round](#operation/broadcastRoundPgn) instead.
      operationId: broadcastAllRoundsPgn
      security: []
      summary: Export all rounds as PGN
      tags:
      - Broadcasts
  /api/simul:
    get:
      description: |
        Get recently finished, ongoing, and upcoming simuls.
      operationId: apiSimul
      security: []
      summary: Get current simuls
      tags:
      - Simuls
  /api/team/{teamId}:
    get:
      description: Infos about a team
      operationId: teamShow
      security: []
      summary: Get a single team
      tags:
      - Teams
  /api/team/all:
    get:
      description: |
        Paginator of the most popular teams.
      operationId: teamAll
      security: []
      summary: Get popular teams
      tags:
      - Teams
  /api/team/of/{username}:
    get:
      description: |
        All the teams a player is a member of.
      operationId: teamOfUsername
      security: []
      summary: Teams of a player
      tags:
      - Teams
  /api/team/search:
    get:
      description: |
        Paginator of team search results for a keyword.
      operationId: teamSearch
      security: []
      summary: Search teams
      tags:
      - Teams
  /api/team/{teamId}/users:
    get:
      description: |
        Members are sorted by reverse chronological order of joining the team (most recent first).
        OAuth only required if the list of members is private.

        Members are streamed as [ndjson](#section/Introduction/Streaming-with-ND-JSON).
      operationId: teamIdUsers
      security:
      - OAuth2:
        - team:read
      summary: Get members of a team
      tags:
      - Users
      - Teams
  /api/team/{teamId}/arena:
    get:
      description: |
        Get all Arena tournaments relevant to a team.

        Tournaments are sorted by reverse chronological order of start date (last starting first).

        Tournaments are streamed as [ndjson](#section/Introduction/Streaming-with-ND-JSON).
      operationId: apiTeamArena
      security: []
      summary: Get team Arena tournaments
      tags:
      - Teams
      - Arena tournaments
  /team/{teamId}/join:
    post:
      description: |
        Join a team.
        If the team requires a password but the `password` field is incorrect,
        then the call fails with `403 Forbidden`.
        Similarly, if the team join policy requires a confirmation but the
        `message` parameter is not given, then the call fails with
        `403 Forbidden`.
      operationId: teamIdJoin
      security:
      - OAuth2:
        - team:write
      summary: Join a team
      tags:
      - Teams
  /team/{teamId}/quit:
    post:
      description: |
        Leave a team.
        - <https://lichess.org/team>
      operationId: teamIdQuit
      security:
      - OAuth2:
        - team:write
      summary: Leave a team
      tags:
      - Teams
  /api/team/{teamId}/requests:
    get:
      description: Get pending join requests of your team
      operationId: teamRequests
      security:
      - OAuth2:
        - team:read
      summary: Get join requests
      tags:
      - Teams
  /api/team/{teamId}/request/{userId}/accept:
    post:
      description: Accept someone's request to join your team
      operationId: teamRequestAccept
      security:
      - OAuth2:
        - team:lead
      summary: Accept join request
      tags:
      - Teams
  /api/team/{teamId}/request/{userId}/decline:
    post:
      description: Decline someone's request to join your team
      operationId: teamRequestDecline
      security:
      - OAuth2:
        - team:lead
      summary: Decline join request
      tags:
      - Teams
  /team/{teamId}/kick/{userId}:
    post:
      description: |
        Kick a member out of one of your teams.
        - <https://lichess.org/team>
      operationId: teamIdKickUserId
      security:
      - OAuth2:
        - team:lead
      summary: Kick a user from your team
      tags:
      - Teams
  /team/{teamId}/pm-all:
    post:
      description: |
        Send a private message to all members of a team.
        You must own the team.
      operationId: teamIdPmAll
      security:
      - OAuth2:
        - team:lead
      summary: Message all members
      tags:
      - Teams
  /api/streamer/live:
    get:
      description: |
        Get basic info about currently streaming users.

        This API is very fast and cheap on lichess side.
        So you can call it quite often (like once every 5 seconds).
      operationId: streamerLive
      security: []
      summary: Get live streamers
      tags:
      - Users
  /api/crosstable/{user1}/{user2}:
    get:
      description: |
        Get total number of games, and current score, of any two users.

        If the `matchup` flag is provided, and the users are currently playing, also gets the current match game number and scores.
      operationId: apiCrosstable
      security: []
      summary: Get crosstable
      tags:
      - Users
  /api/rel/following:
    get:
      description: |
        Users are streamed as [ndjson](#section/Introduction/Streaming-with-ND-JSON).
      operationId: apiUserFollowing
      security:
      - OAuth2:
        - follow:read
      summary: Get users followed by the logged in user
      tags:
      - Relations
  /api/rel/follow/{username}:
    post:
      description: |
        Follow a player, adding them to your list of Lichess friends.
      operationId: followUser
      security:
      - OAuth2:
        - follow:write
      summary: Follow a player
      tags:
      - Relations
  /api/rel/unfollow/{username}:
    post:
      description: |
        Unfollow a player, removing them from your list of Lichess friends.
      operationId: unfollowUser
      security:
      - OAuth2:
        - follow:write
      summary: Unfollow a player
      tags:
      - Relations
  /api/stream/event:
    get:
      description: "\n  Stream the events reaching a lichess user in real time as\
        \ [ndjson](#section/Introduction/Streaming-with-ND-JSON).\n\n  Each line is\
        \ a JSON object containing a `type` field. Possible values are:\n  - `gameStart`\
        \ Start of a game\n  - `gameFinish` Completion of a game\n  - `challenge`\
        \ A player sends you a challenge or you challenge someone\n  - `challengeCanceled`\
        \ A player cancels their challenge to you\n  - `challengeDeclined` The opponent\
        \ declines your challenge\n \n  When the stream opens, all current challenges\
        \ and games are sent."
      operationId: apiStreamEvent
      security:
      - OAuth2:
        - challenge:read
        - bot:play
        - board:play
      summary: Stream incoming events
      tags:
      - Board
      - Bot
  /api/board/seek:
    post:
      description: |2-

          Create a public seek, to start a game with a random player.

          ### Real-time seek

          Specify the `time` and `increment` clock values.  The response is streamed but doesn't contain any information.

          **Keep the connection open to keep the seek active**.

          If the client closes the connection, the seek is canceled. This way, if the client terminates, the user won't be paired in a game they wouldn't play.
          When the seek is accepted, or expires, the server closes the connection.

          **Make sure to also have an [Event stream](#operation/apiStreamEvent) open**, to be notified when a game starts.
          We recommend opening the [Event stream](#operation/apiStreamEvent) first, then the seek stream. This way,
          you won't miss the game event if the seek is accepted immediately.

          ### Correspondence seek

          Specify the `days` per turn value.  The response is not streamed, it immediately completes with the seek ID. The seek remains active on the server until it is joined by someone.
      operationId: apiBoardSeek
      security:
      - OAuth2:
        - board:play
      summary: Create a seek
      tags:
      - Board
  /api/board/game/stream/{gameId}:
    get:
      description: " Stream the state of a game being played with the Board API, as\
        \ [ndjson](#section/Introduction/Streaming-with-ND-JSON).\n\nUse this endpoint\
        \ to get updates about the game in real-time, with a single request.\n\nEach\
        \ line is a JSON object containing a `type` field. Possible values are:\n\
        \  - `gameFull` Full game data. All values are immutable, except for the `state`\
        \ field.\n  - `gameState` Current state of the game. Immutable values not\
        \ included. Sent when a move is played, a draw is offered, or when the game\
        \ ends.\n  - `chatLine` Chat message sent by a user in the `room` \"player\"\
        \ or \"spectator\".\n\n  - `opponentGone` Whether the opponent has left the\
        \ game, and how long before you can claim a win or draw.\n\n \nThe first line\
        \ is always of type `gameFull`.\n\n \nThe server closes the stream when the\
        \ game ends, or if the game has already ended."
      operationId: boardGameStream
      security:
      - OAuth2:
        - board:play
      summary: Stream Board game state
      tags:
      - Board
  /api/board/game/{gameId}/move/{move}:
    post:
      description: |
        Make a move in a game being played with the Board API.

        The move can also contain a draw offer/agreement.
      operationId: boardGameMove
      security:
      - OAuth2:
        - board:play
      summary: Make a Board move
      tags:
      - Board
  /api/board/game/{gameId}/chat:
    get:
      description: |
        Get the messages posted in the game chat
      operationId: boardGameChatGet
      security:
      - OAuth2:
        - board:play
      summary: Fetch the game chat
      tags:
      - Board
    post:
      description: |
        Post a message to the player or spectator chat, in a game being played with the Board API.
      operationId: boardGameChatPost
      security:
      - OAuth2:
        - board:play
      summary: Write in the chat
      tags:
      - Board
  /api/board/game/{gameId}/abort:
    post:
      description: |
        Abort a game being played with the Board API.
      operationId: boardGameAbort
      security:
      - OAuth2:
        - board:play
      summary: Abort a game
      tags:
      - Board
  /api/board/game/{gameId}/resign:
    post:
      description: |
        Resign a game being played with the Board API.
      operationId: boardGameResign
      security:
      - OAuth2:
        - board:play
      summary: Resign a game
      tags:
      - Board
  /api/board/game/{gameId}/draw/{accept}:
    post:
      description: |
        Create/accept/decline draw offers.
        - `yes`: Offer a draw, or accept the opponent's draw offer.
        - `no`: Decline a draw offer from the opponent.
      operationId: boardGameDraw
      security:
      - OAuth2:
        - board:play
      summary: Handle draw offers
      tags:
      - Board
  /api/board/game/{gameId}/takeback/{accept}:
    post:
      description: |
        Create/accept/decline takebacks.
        - `yes`: Propose a takeback, or accept the opponent's takeback offer.
        - `no`: Decline a takeback offer from the opponent.
      operationId: boardGameTakeback
      security:
      - OAuth2:
        - board:play
      summary: Handle takeback offers
      tags:
      - Board
  /api/board/game/{gameId}/claim-victory:
    post:
      description: |
        Claim victory when the opponent has left the game for a while.
      operationId: boardGameClaimVictory
      security:
      - OAuth2:
        - board:play
      summary: Claim victory of a game
      tags:
      - Board
  /api/board/game/{gameId}/berserk:
    post:
      description: |
        Go berserk on an arena tournament game. Halves the clock time, grants an extra point upon winning.
        Only available in arena tournaments that allow berserk, and before each player has made a move.
      operationId: boardGameBerserk
      security:
      - OAuth2:
        - board:play
      summary: Berserk a tournament game
      tags:
      - Board
  /api/bot/online:
    get:
      description: "Stream the [online bot users](https://lichess.org/player/bots),\
        \ as [ndjson](#section/Introduction/Streaming-with-ND-JSON). Throttled to\
        \ 50 bot users per second."
      operationId: apiBotOnline
      security: []
      summary: Get online bots
      tags:
      - Bot
  /api/bot/account/upgrade:
    post:
      description: |
        Upgrade a lichess player account into a Bot account. Only Bot accounts can use the Bot API.

        The account **cannot have played any game** before becoming a Bot account. The upgrade is **irreversible**. The account will only be able to play as a Bot.

        To upgrade an account to Bot, use the [official lichess-bot client](https://github.com/ShailChoksi/lichess-bot), or follow these steps:
        - Create an [API access token](https://lichess.org/account/oauth/token/create?scopes[]=bot:play) with "Play bot moves" permission.
        - `curl -d '' https://lichess.org/api/bot/account/upgrade -H "Authorization: Bearer <yourTokenHere>"`

        To know if an account has already been upgraded, use the [Get my profile API](#operation/accountMe):
        the `title` field should be set to `BOT`.
      operationId: botAccountUpgrade
      security:
      - OAuth2:
        - bot:play
      summary: Upgrade to Bot account
      tags:
      - Bot
  /api/bot/game/stream/{gameId}:
    get:
      description: " Stream the state of a game being played with the Bot API, as\
        \ [ndjson](#section/Introduction/Streaming-with-ND-JSON).\n\nUse this endpoint\
        \ to get updates about the game in real-time, with a single request.\n\nEach\
        \ line is a JSON object containing a `type` field. Possible values are:\n\
        \  - `gameFull` Full game data. All values are immutable, except for the `state`\
        \ field.\n  - `gameState` Current state of the game. Immutable values not\
        \ included.\n  - `chatLine` Chat message sent by a user (or the bot itself)\
        \ in the `room` \"player\" or \"spectator\".\n\n  - `opponentGone` Whether\
        \ the opponent has left the game, and how long before you can claim a win\
        \ or draw.\n\n \nThe first line is always of type `gameFull`."
      operationId: botGameStream
      security:
      - OAuth2:
        - bot:play
      summary: Stream Bot game state
      tags:
      - Bot
  /api/bot/game/{gameId}/move/{move}:
    post:
      description: |
        Make a move in a game being played with the Bot API.

        The move can also contain a draw offer/agreement.
      operationId: botGameMove
      security:
      - OAuth2:
        - bot:play
      summary: Make a Bot move
      tags:
      - Bot
  /api/bot/game/{gameId}/chat:
    get:
      description: |
        Get the messages posted in the game chat
      operationId: botGameChatGet
      security:
      - OAuth2:
        - bot:play
      summary: Fetch the game chat
      tags:
      - Bot
    post:
      description: |
        Post a message to the player or spectator chat, in a game being played with the Bot API.
      operationId: botGameChat
      security:
      - OAuth2:
        - bot:play
      summary: Write in the chat
      tags:
      - Bot
  /api/bot/game/{gameId}/abort:
    post:
      description: |
        Abort a game being played with the Bot API.
      operationId: botGameAbort
      security:
      - OAuth2:
        - bot:play
      summary: Abort a game
      tags:
      - Bot
  /api/bot/game/{gameId}/resign:
    post:
      description: |
        Resign a game being played with the Bot API.
      operationId: botGameResign
      security:
      - OAuth2:
        - bot:play
      summary: Resign a game
      tags:
      - Bot
  /api/challenge:
    get:
      description: |
        Get a list of challenges created by or targeted at you.
      operationId: challengeList
      security:
      - OAuth2:
        - challenge:read
      summary: List your challenges
      tags:
      - Challenges
  /api/challenge/{username}:
    post:
      description: |
        Challenge someone to play. The targeted player can choose to accept or decline.

        If the challenge is accepted, you will be notified on the [event stream](#operation/apiStreamEvent)
        that a new game has started. The game ID will be the same as the challenge ID.

        If you also have an OAuth token with `challenge:write` scope for the receiving user,
        you can make them accept the challenge immediately by setting the `acceptByToken` field.

        Challenges for realtime games (not correspondence) expire after 20s if not accepted.
        To prevent that, use the `keepAliveStream` flag described below.
      operationId: challengeCreate
      security:
      - OAuth2:
        - challenge:write
        - bot:play
        - board:play
      summary: Create a challenge
      tags:
      - Challenges
  /api/challenge/{challengeId}/accept:
    post:
      description: |
        Accept an incoming challenge.

        You should receive a `gameStart` event on the [incoming events stream](#operation/apiStreamEvent).
      operationId: challengeAccept
      security:
      - OAuth2:
        - challenge:write
        - bot:play
        - board:play
      summary: Accept a challenge
      tags:
      - Challenges
  /api/challenge/{challengeId}/decline:
    post:
      description: |
        Decline an incoming challenge.
      operationId: challengeDecline
      security:
      - OAuth2:
        - challenge:write
        - bot:play
        - board:play
      summary: Decline a challenge
      tags:
      - Challenges
  /api/challenge/{challengeId}/cancel:
    post:
      description: |
        Cancel a challenge you sent, or aborts the game if the challenge was accepted, but the game was not yet played.
        Note that the ID of a game is the same as the ID of the challenge that created it.
      operationId: challengeCancel
      security:
      - OAuth2:
        - challenge:write
        - bot:play
        - board:play
      summary: Cancel a challenge
      tags:
      - Challenges
  /api/challenge/ai:
    post:
      description: |
        Start a game with Lichess AI.

        You will be notified on the [event stream](#operation/apiStreamEvent) that a new game has started.
      operationId: challengeAi
      security:
      - OAuth2:
        - challenge:write
        - bot:play
        - board:play
      summary: Challenge the AI
      tags:
      - Challenges
  /api/challenge/open:
    post:
      description: |
        Create a challenge that any 2 players can join.

        Share the URL of the challenge. the first 2 players to click it will be paired for a game.

        The response body also contains `whiteUrl` and `blackUrl`.
        You can control which color each player gets by giving them these URLs,
        instead of the main challenge URL.

        Open challenges expire after 24h.

        To directly pair 2 known players, use [this endpoint](#operation/challengeCreate) instead,
        with the `acceptByToken` parameter.
      operationId: challengeOpen
      security: []
      summary: Open-ended challenge
      tags:
      - Challenges
  /api/challenge/{gameId}/start-clocks:
    post:
      description: |
        Start the clocks of a game immediately, even if a player has not yet made a move.

        Requires the OAuth tokens of both players with `challenge:write` scope.

        If the clocks have already started, the call will have no effect.
      operationId: challengeStartClocks
      security:
      - OAuth2:
        - challenge:write
      summary: Start clocks of a game
      tags:
      - Challenges
  /api/bulk-pairing:
    get:
      description: |
        Get a list of upcoming bulk pairings you created.

        Only bulk pairings that are scheduled in the future, or that have a clock start scheduled in the future, are listed.

        Bulk pairings are deleted from the server after the pairings are done and the clocks have started.
      operationId: bulkPairingGet
      security:
      - OAuth2:
        - challenge:bulk
      summary: View upcoming bulk pairings
      tags:
      - Bulk pairings
    post:
      description: |
        Schedule many games at once, up to 24h in advance.

        OAuth tokens are required for all paired players, with the `challenge:write` scope.

        You can schedule up to 500 games every 10 minutes. [Contact us](mailto:contact@lichess.org) if you need higher limits.

        If games have a real-time clock, each player must have only one pairing.
        For correspondence games, players can have multiple pairings within the same bulk.

        The entire bulk is rejected if:
          - a token is missing
          - a token is present more than once (except in correspondence)
          - a token lacks the `challenge:write` scope
          - a player account is closed
          - a player is paired more than once (except in correspondence)
          - a bulk is already scheduled to start at the same time with the same player
          - you have 10 scheduled bulks
          - you have 1000 scheduled games

        Partial bulks are never created. Either it all fails, or it all succeeds.
        When it fails, it does so with an error message explaining the issue.
        Failed bulks are not counted in the rate limiting, they are free.
        Fix the issues, manually or programmatically, then retry to schedule the bulk.

        A successful bulk creation returns a JSON bulk document. Its ID can be used for further operations.
      operationId: bulkPairingCreate
      security:
      - OAuth2:
        - challenge:bulk
      summary: Create a bulk pairing
      tags:
      - Bulk pairings
  /api/bulk-pairing/{id}/start-clocks:
    post:
      description: |
        Immediately start all clocks of the games of a bulk pairing.

        This overrides the `startClocksAt` value of an existing bulk pairing.

        If the games have not yet been created (`bulk.pairAt` is in the future), then this does nothing.

        If the clocks have already started (`bulk.startClocksAt` is in the past), then this does nothing.
      operationId: bulkPairingStartClocks
      security:
      - OAuth2:
        - challenge:bulk
      summary: Manually start clocks
      tags:
      - Bulk pairings
  /api/bulk-pairing/{id}:
    delete:
      description: |
        Cancel and delete a bulk pairing that is scheduled in the future.

        If the games have already been created, then this does nothing.

        Canceling a bulk pairing does not refund the rate limit cost of that bulk pairing.
      operationId: bulkPairingDelete
      security:
      - OAuth2:
        - challenge:bulk
      summary: Cancel a bulk pairing
      tags:
      - Bulk pairings
  /api/round/{gameId}/add-time/{seconds}:
    post:
      description: |
        Add seconds to the opponent's clock. Can be used to create games with time odds.
      operationId: roundAddTime
      security:
      - OAuth2:
        - challenge:write
      summary: Add time to the opponent clock
      tags:
      - Challenges
  /api/token/admin-challenge:
    post:
      description: |
        **This endpoint can only be used by Lichess administrators. It will not work if you do not have the appropriate permissions.** Tournament organizers should instead use [OAuth](#tag/OAuth) to obtain `challenge:write` tokens from users in order to perform bulk pairing.*

        Create and obtain `challenge:write` tokens for multiple users.

        If a similar token already exists for a user, it is reused. This endpoint is idempotent.
      operationId: adminChallengeTokens
      security:
      - OAuth2:
        - web:mod
      summary: Admin challenge tokens
      tags:
      - Challenges
  /inbox/{username}:
    post:
      description: |
        Send a private message to another player.
      operationId: inboxUsername
      security:
      - OAuth2:
        - msg:write
      summary: Send a private message
      tags:
      - Messaging
  /api/cloud-eval:
    get:
      description: |
        Get the cached evaluation of a position, if available.

        Opening positions have more chances of being available. There are about 15 million positions in the database.

        Up to 5 variations may be available. Variants are supported.
      operationId: apiCloudEval
      security: []
      summary: Get cloud evaluation of a position.
      tags:
      - Analysis
  /api/external-engine:
    get:
      description: |
        Lists all external engines that have been registered for the user,
        and the credentials required to use them.
      operationId: apiExternalEngineList
      security:
      - OAuth2:
        - engine:read
      summary: List external engines
      tags:
      - External engine
    post:
      description: |
        Registers a new external engine for the user. It can then be selected
        and used on the analysis board.

        After registering, the provider should start waiting for analyis requests.
      operationId: apiExternalEngineCreate
      security:
      - OAuth2:
        - engine:write
      summary: Create external engine
      tags:
      - External engine
  /api/external-engine/{id}:
    delete:
      description: |
        Unregisters an external engine.
      operationId: apiExternalEngineDelete
      security:
      - OAuth2:
        - engine:write
      summary: Delete external engine
      tags:
      - External engine
    get:
      description: |
        Get properties and credentials of an external engine.
      operationId: apiExternalEngineGet
      security:
      - OAuth2:
        - engine:read
      summary: Get external engine
      tags:
      - External engine
    put:
      description: |
        Updates the properties of an external engine.
      operationId: apiExternalEnginePut
      security:
      - OAuth2:
        - engine:write
      summary: Update external engine
      tags:
      - External engine
  /api/external-engine/{id}/analyse:
    post:
      description: "**Endpoint: `https://engine.lichess.ovh/api/external-engine/{id}/analyse`**\n\
        \nRequest analysis from an external engine.\n\nResponse content is streamed\
        \ as [newline delimited JSON](#section/Introduction/Streaming-with-ND-JSON).\
        \ \nThe properties are based on the [UCI specification](https://backscattering.de/chess/uci/#engine).\n\
        Analysis stops when the client goes away, the requested limit\nis reached,\
        \ or the provider goes away.\n"
      operationId: apiExternalEngineAnalyse
      security: []
      summary: Analyse with external engine
      tags:
      - External engine
    servers:
    - url: https://engine.lichess.ovh
  /api/external-engine/work:
    post:
      description: |
        **Endpoint: `https://engine.lichess.ovh/api/external-engine/work`**

        Wait for an analysis requests to any of the external engines that
        have been registered with the given `secret`.

        Uses long polling.

        After acquiring a request, the provider should immediately
        [start streaming the results](#tag/External-engine/operation/apiExternalEngineSubmit).
      operationId: apiExternalEngineAcquire
      security: []
      summary: Acquire analysis request
      tags:
      - External engine
    servers:
    - url: https://engine.lichess.ovh
  /api/external-engine/work/{id}:
    post:
      description: |
        **Endpoint: `https://engine.lichess.ovh/api/external-engine/work/{id}`**

        Submit a stream of analysis as [UCI output](https://backscattering.de/chess/uci/#engine-info).

        * The engine should always be in `UCI_Chess960` mode.
        * `UCI_AnalyseMode` enabled if available.
        * It produces `info` with at least:
          - `depth`
          - `multipv` (between 1 and 5)
          - `score`
          - `nodes`
          - `time`
          - `pv`

        The server may close the connection at any time, indicating that
        the requester has gone away and analysis should be stopped.
      operationId: apiExternalEngineSubmit
      security: []
      summary: Answer analysis request
      tags:
      - External engine
    servers:
    - url: https://engine.lichess.ovh
  /oauth:
    get:
      description: |
        OAuth2 authorization endpoint.

        Start the OAuth2 Authorization Code Flow with PKCE by securely
        generating two random strings unique to each authorization
        * `code_verifier`
        * `state`

        Store these in session storage. Make sure not to reveal `code_verifier`
        to eavesdroppers. Do not show it in URLs, do not abuse `state` to store
        it, do not send it over insecure connections. However it is fine if
        the user themselves can extract `code_verifier`, which will always be
        possible for fully client-side apps.

        Then send the user to this endpoint. They will be prompted to grant
        authorization and then be redirected back to the given `redirect_uri`.

        If the authorization failed, the following query string parameters will
        be appended to the redirection:
        * `error`, in particular with value `access_denied` if the user
           cancelled authorization
        * `error_description` to aid debugging
        * `state`, exactly as passed in the `state` parameter

        If the authorization succeeded, the following query string parameters
        will be appended to the redirection:
        * `code`, containing a fresh short-lived authorization code
        * `state`, exactly as passed in the `state` parameter

        Next, to defend against cross site request forgery, check that the
        returned `state` matches the `state` you originally generated.

        Finally, continue by using the authorization code to
        [obtain an access token](#operation/apiToken).
      operationId: oauth
      security: []
      summary: Request authorization code
      tags:
      - OAuth
  /api/token:
    delete:
      description: Revokes the access token sent as Bearer for this request.
      operationId: apiTokenDelete
      security:
      - OAuth2: []
      summary: Revoke access token
      tags:
      - OAuth
    post:
      description: |
        OAuth2 token endpoint. Exchanges an authorization code for an access token.
      operationId: apiToken
      security: []
      summary: Obtain access token
      tags:
      - OAuth
  /api/token/test:
    post:
      description: "For up to 1000 OAuth tokens, \nreturns their associated user ID\
        \ and scopes,\nor `null` if the token is invalid.\n\nThe method is `POST`\
        \ so a longer list of tokens can be sent in the request body.\n"
      operationId: tokenTest
      security: []
      summary: Test multiple OAuth tokens
      tags:
      - OAuth
  /masters:
    get:
      description: |
        **Endpoint: <https://explorer.lichess.ovh/masters>**

        Example: `curl https://explorer.lichess.ovh/masters?play=d2d4,d7d5,c2c4,c7c6,c4d5`
      operationId: openingExplorerMaster
      security: []
      summary: Masters database
      tags:
      - Opening Explorer
    servers:
    - url: https://explorer.lichess.ovh
  /lichess:
    get:
      description: |
        **Endpoint: <https://explorer.lichess.ovh/lichess>**

        Games sampled from all Lichess players.

        Example: `curl https://explorer.lichess.ovh/lichess?variant=standard&speeds=blitz,rapid,classical&ratings=2200,2500&fen=rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR%20w%20KQkq%20-%200%201`
      operationId: openingExplorerLichess
      security: []
      summary: Lichess games
      tags:
      - Opening Explorer
    servers:
    - url: https://explorer.lichess.ovh
  /lichess/history:
    get:
      description: |
        **Endpoint: <https://explorer.lichess.ovh/lichess/history>**

        Opening statistics of games sampled from all Lichess players, grouped
        by month. Starts with the first month that has any data,
        or at `since` if given.
      operationId: openingExplorerLichessHistory
      security: []
      summary: Lichess games history
      tags:
      - Opening Explorer
    servers:
    - url: https://explorer.lichess.ovh
  /player:
    get:
      description: |
        **Endpoint: <https://explorer.lichess.ovh/player>**

        Games of a Lichess player.

        Responds with a stream of [newline delimited JSON](#section/Introduction/Streaming-with-ND-JSON). Will start indexing
        on demand, immediately respond with the current results, and stream
        more updates until indexing is complete. The stream is throttled
        and deduplicated. Empty lines may be sent to avoid timeouts.

        Will index new games at most once per minute, and revisit previously
        ongoing games at most once every day.

        Example: `curl https://explorer.lichess.ovh/player?player=revoof&color=white&play=d2d4,d7d5&recentGames=1`
      operationId: openingExplorerPlayer
      security: []
      summary: Player games
      tags:
      - Opening Explorer
    servers:
    - url: https://explorer.lichess.ovh
  /master/pgn/{gameId}:
    get:
      description: |
        **Endpoint: `https://explorer.lichess.ovh/masters/pgn/{gameId}`**

        Example: `curl https://explorer.lichess.ovh/masters/pgn/aAbqI4ey`
      operationId: openingExplorerMasterGame
      security: []
      summary: OTB master game
      tags:
      - Opening Explorer
    servers:
    - url: https://explorer.lichess.ovh
  /standard:
    get:
      description: |
        **Endpoint: <https://tablebase.lichess.ovh>**

        Example: `curl http://tablebase.lichess.ovh/standard?fen=4k3/6KP/8/8/8/8/7p/8_w_-_-_0_1`
      operationId: tablebaseStandard
      security: []
      summary: Tablebase lookup
      tags:
      - Tablebase
    servers:
    - url: https://tablebase.lichess.ovh
  /atomic:
    get:
      description: |
        **Endpoint: <https://tablebase.lichess.ovh>**
      operationId: tablebaseAtomic
      summary: Tablebase lookup for Atomic chess
      tags:
      - Tablebase
    servers:
    - url: https://tablebase.lichess.ovh
  /antichess:
    get:
      description: |
        **Endpoint: <https://tablebase.lichess.ovh>**
      operationId: antichessAtomic
      summary: Tablebase lookup for Antichess
      tags:
      - Tablebase
    servers:
    - url: https://tablebase.lichess.ovh
components:
  securitySchemes:
    OAuth2:
      description: |
        ### Which authentication method is right for me?
        [Read about the Lichess API authentication methods and code examples](https://github.com/lichess-org/api/blob/master/example/README.md)

        ### Personal Access Token
        Personal API access tokens allow you to quickly interact with Lichess API without going through an OAuth flow.
        - [Generate a personal access token](https://lichess.org/account/oauth/token)
        - `curl https://lichess.org/api/account -H "Authorization: Bearer {token}"`
        - [NodeJS example](https://github.com/lichess-org/api/tree/master/example/oauth-personal-token)

        ### Authorization Code Flow with PKCE
        The authorization code flow with PKCE allows your users to **login with Lichess**.
        Lichess supports unregistered and public clients (no client authentication, choose any unique client id).
        The only accepted code challenge method is `S256`.
        Access tokens are long-lived (expect one year), unless they are revoked.
        Refresh tokens are not supported.

        See the [documentation for the OAuth endpoints](#tag/OAuth) or
        the [PKCE RFC](https://datatracker.ietf.org/doc/html/rfc7636#section-4) for a precise protocol description.

        - [Demo app](https://lichess-org.github.io/api-demo/)
        - [Minimal client-side example](https://github.com/lichess-org/api/tree/master/example/oauth-app)
        - [Flask/Python example](https://github.com/lakinwecker/lichess-oauth-flask)
        - [Java example](https://github.com/tors42/lichess-oauth-pkce-app)
        - [NodeJS Passport strategy to login with Lichess OAuth2](https://www.npmjs.com/package/passport-lichess)

        #### Real life examples
        - [PyChess](https://github.com/gbtami/pychess-variants) ([source code](https://github.com/gbtami/pychess-variants))
        - [Lichess4545](https://www.lichess4545.com/) ([source code](https://github.com/cyanfish/heltour))
        - [English Chess Federation](https://ecf.octoknight.com/)
        - [Rotherham Online Chess](https://rotherhamonlinechess.azurewebsites.net/tournaments)

        ### Token format
        Access tokens and authorization codes match `^[A-Za-z0-9_]+$`.
        The length of tokens can be increased without notice. Make sure your application can handle at least 512 characters.
        By convention tokens have a recognizable prefix, but do not rely on this.
      flows:
        authorizationCode:
          authorizationUrl: https://lichess.org/oauth
          scopes:
            preference:read: Read your preferences
            preference:write: Write your preferences
            email:read: Read your email address
            challenge:read: Read incoming challenges
            challenge:write: "Create, accept, decline challenges"
            challenge:bulk: "Create, delete, query bulk pairings"
            study:read: Read private studies and broadcasts
            study:write: "Create, update, delete studies and broadcasts"
            tournament:write: Create tournaments
            racer:write: Create and join puzzle races
            puzzle:read: Read puzzle activity
            team:read: Read private team information
            team:write: "Join, leave teams"
            team:lead: "Manage teams (kick members, send PMs)"
            follow:read: Read followed players
            follow:write: Follow and unfollow other players
            msg:write: Send private messages to other players
            board:play: Play with the Board API
            bot:play: "Play with the Bot API. Only for [Bot accounts](#operation/botAccountUpgrade)"
            web:mod: Use moderator tools (within the bounds of your permissions)
          tokenUrl: https://lichess.org/api/token
      type: oauth2
